### ISSUE TITLE
Where can I get the CGC_flagship.missense_variants_snpEff_snpSift_GoNLv5.header.vcf file?

### ISSUE THREAD

**Issue by rezacsedu** [UMCUGenetics/FairDNA#1]
Hi there,

I was trying to reuse this script for VCF to RDF conversion. 
Could you please let me know where can I get the CGC_flagship.missense_variants_snpEff_snpSift_GoNLv5.header.vcf file?

Best,

**Comment by jdeligt** [comment]
I uploaded a sample of this file for testing purposes, we'll try to get the full version hosted sowhere, it's a bit big for git. see latest commit: 4532ad8a95c9b8915b294a443c0539a56bd466ad

**Comment by rezacsedu** [comment]
@jdeligt 
Thanks for quick response. However, I would ask for another favor, please. When I run this script on the data file you just uploaded, I am experiencing the following error: 

```
root@ubuntu:~$ python3 parseVCF.py 
Traceback (most recent call last):
  File "parseVCF.py", line 42, in <module>
    vcf_reader = vcf.Reader(open('CGC_flagship.missense_variants_snpEff_snpSift_GoNLv5.header.vcf', 'r'))
  File "/usr/lib/python3/dist-packages/vcf/parser.py", line 288, in __init__
    self._parse_metainfo()
  File "/usr/lib/python3/dist-packages/vcf/parser.py", line 309, in _parse_metainfo
    key, val = parser.read_info(line)
  File "/usr/lib/python3/dist-packages/vcf/parser.py", line 123, in read_info
    "One of the INFO lines is malformed: %s" % info_string)
SyntaxError: One of the INFO lines is malformed: ##INFO=<ID=GoNLv5_AC, Number=A, Type=Integer, Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
```


Any pointer would be highly appreciated.

**Comment by rernst** [comment]
Which version of pyvcf do you use? I am using 0.6.8 (latest) and the vcf loads just fine.

**Comment by jdeligt** [comment]
@rezacsedu could you please verify if this resolved your issue?

**Comment by rezacsedu** [comment]
@jdeligt @rernst pyvcf  v0.6.8 worked fine and solved the issue. Thanks so much for your support.

**Comment by jdeligt** [comment]
Hi @rezacsedu, glad this worked, FYI the data is available on our bitbucket:
https://bitbucket.org/evertbosdriesz/cgc-multi-omics/overview

**Comment by rezacsedu** [comment]
Hi @jdeligt, that's a great news! Thanks for the sharing the link :) 
By the way, is this a private repo? I cannot access.
